"""D6 bounded first-slice tests (docs/DECISIONS.md; interface + fake only).

Only an in-process fake provider is used here — app/github_publication.py
itself registers no concrete implementation, contacts no network, and is not
imported by any approval/API/execution code path (grep-checked below).
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

from app.github_publication import (
    DraftPullRequestRequest,
    DraftPullRequestResult,
    GitHubPublicationProvider,
)


class FakeGitHubPublicationProvider(GitHubPublicationProvider):
    """In-process test double. Never touches a network or a real credential."""

    def __init__(self, *, next_pull_request_number: int = 1):
        self._next_pull_request_number = next_pull_request_number
        self.received_requests: list[DraftPullRequestRequest] = []

    @property
    def provider_id(self) -> str:
        return "fake-github-v1"

    def create_draft_pull_request(
        self, request: DraftPullRequestRequest
    ) -> DraftPullRequestResult:
        self.received_requests.append(request)
        number = self._next_pull_request_number
        self._next_pull_request_number += 1
        return DraftPullRequestResult(
            provider_id=self.provider_id,
            repository=request.repository,
            pull_request_number=number,
            pull_request_url=(
                f"https://example.invalid/{request.repository}/pull/{number}"
            ),
            head_branch=request.head_branch,
            is_draft=True,
        )


def _request(**overrides) -> DraftPullRequestRequest:
    values = dict(
        repository="octo/example",
        base_branch="main",
        head_branch="engineering-task/123",
        title="Automated change",
        body="Generated by an Engineering Task run.",
        bundle_ref="sha256:" + "a" * 64,
    )
    values.update(overrides)
    return DraftPullRequestRequest(**values)


# ---------------------------------------------------------------------------
# Request/result validation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "field",
    ["repository", "base_branch", "head_branch", "title", "bundle_ref"],
)
def test_request_rejects_blank_required_fields(field):
    with pytest.raises(ValueError, match="non-empty string"):
        _request(**{field: "   "})


def test_request_allows_empty_body():
    request = _request(body="")
    assert request.body == ""


def test_request_rejects_non_string_body():
    with pytest.raises(ValueError, match="body must be a string"):
        _request(body=None)


def test_request_is_immutable():
    request = _request()
    with pytest.raises(Exception):
        request.title = "tampered"  # type: ignore[misc]


def test_result_rejects_non_draft():
    with pytest.raises(ValueError, match="only ever represents draft"):
        DraftPullRequestResult(
            provider_id="fake-github-v1",
            repository="octo/example",
            pull_request_number=1,
            pull_request_url="https://example.invalid/octo/example/pull/1",
            head_branch="engineering-task/123",
            is_draft=False,
        )


def test_result_rejects_non_positive_pull_request_number():
    with pytest.raises(ValueError, match="positive"):
        DraftPullRequestResult(
            provider_id="fake-github-v1",
            repository="octo/example",
            pull_request_number=0,
            pull_request_url="https://example.invalid/octo/example/pull/0",
            head_branch="engineering-task/123",
            is_draft=True,
        )


@pytest.mark.parametrize(
    "field", ["provider_id", "repository", "pull_request_url", "head_branch"]
)
def test_result_rejects_blank_required_fields(field):
    values = dict(
        provider_id="fake-github-v1",
        repository="octo/example",
        pull_request_number=1,
        pull_request_url="https://example.invalid/octo/example/pull/1",
        head_branch="engineering-task/123",
        is_draft=True,
    )
    values[field] = ""
    with pytest.raises(ValueError, match="non-empty string"):
        DraftPullRequestResult(**values)


# ---------------------------------------------------------------------------
# Interface shape: exactly one operation, never merge/deploy/push, no
# credential field.
# ---------------------------------------------------------------------------


def test_interface_exposes_exactly_one_operation():
    abstract_members = GitHubPublicationProvider.__abstractmethods__
    assert abstract_members == {"provider_id", "create_draft_pull_request"}


def test_interface_has_no_merge_deploy_or_push_shaped_method():
    forbidden_substrings = ("merge", "deploy", "push", "publish_direct")
    members = [name for name in dir(GitHubPublicationProvider) if not name.startswith("_")]
    for member in members:
        lowered = member.lower()
        assert not any(bad in lowered for bad in forbidden_substrings), member


def test_request_and_result_have_no_credential_shaped_field():
    forbidden_substrings = ("token", "secret", "credential", "password", "key")
    for cls in (DraftPullRequestRequest, DraftPullRequestResult):
        for field_name in cls.__dataclass_fields__:
            lowered = field_name.lower()
            assert not any(bad in lowered for bad in forbidden_substrings), (
                cls.__name__,
                field_name,
            )


def test_module_contacts_no_network_and_is_not_wired_into_production_paths():
    """Static, source-level check: no HTTP client import in the module, and
    no other app module imports it — this bounded slice is deliberately
    unreachable from any approval/API/execution code path."""

    module_path = (
        Path(__file__).resolve().parent.parent / "app" / "github_publication.py"
    )
    source = module_path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    imported_names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported_names.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported_names.add(node.module.split(".")[0])
    forbidden_modules = {"httpx", "requests", "urllib", "socket", "asyncssh", "app"}
    assert imported_names.isdisjoint(forbidden_modules)

    app_dir = module_path.parent
    for other_path in app_dir.glob("*.py"):
        if other_path.name in {"github_publication.py", "__init__.py"}:
            continue
        other_source = other_path.read_text(encoding="utf-8")
        other_tree = ast.parse(other_source)
        for node in ast.walk(other_tree):
            if isinstance(node, ast.ImportFrom) and node.module == "app.github_publication":
                pytest.fail(
                    f"{other_path.name} imports app.github_publication;"
                    " this bounded D6 slice must stay unwired"
                )
            if isinstance(node, ast.Import):
                for alias in node.names:
                    assert alias.name != "app.github_publication", other_path.name


# ---------------------------------------------------------------------------
# Fake provider round trip
# ---------------------------------------------------------------------------


def test_fake_provider_creates_a_draft_pull_request():
    provider = FakeGitHubPublicationProvider(next_pull_request_number=42)
    request = _request()

    result = provider.create_draft_pull_request(request)

    assert result.is_draft is True
    assert result.provider_id == "fake-github-v1"
    assert result.repository == "octo/example"
    assert result.pull_request_number == 42
    assert result.head_branch == "engineering-task/123"
    assert provider.received_requests == [request]


def test_fake_provider_never_merges_or_reuses_pull_request_numbers():
    provider = FakeGitHubPublicationProvider()
    first = provider.create_draft_pull_request(_request())
    second = provider.create_draft_pull_request(_request(head_branch="other-branch"))

    assert first.pull_request_number != second.pull_request_number
    assert {first.is_draft, second.is_draft} == {True}
