#!/usr/bin/env bash
# Local preview of dispatch-center: an ISOLATED backend + Vite dev server with
# hot reload, auto-authenticated as a seeded preview admin. Never touches the
# pilot (/home/aied/pilot-run) or any real worker.
#
#   preview.sh start     start backend (127.0.0.1:8001) + Vite (127.0.0.1:5173)
#   preview.sh stop      stop both
#   preview.sh restart   stop + start
#   preview.sh status    pids, health, URL
#   preview.sh logs      tail backend + vite logs
#   preview.sh reset     stop, wipe .runtime/preview (fresh DB), start
#   preview.sh cookie    print the seeded session cookie (for curl/Playwright)
#
# Everything lives under <repo>/.runtime/preview (gitignored): .env, DB, audit,
# servers.yaml, keys/, home/ (AI usage scan dir), logs, pids, session cookie.
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
RUNTIME_DIR="$ROOT_DIR/.runtime/preview"
PY="$ROOT_DIR/.venv/bin/python"
API_HOST="127.0.0.1"
API_PORT="${PREVIEW_API_PORT:-8001}"
VITE_PORT="${PREVIEW_VITE_PORT:-5173}"
BACKEND_PID="$RUNTIME_DIR/backend.pid"
VITE_PID="$RUNTIME_DIR/vite.pid"
BACKEND_LOG="$RUNTIME_DIR/backend.log"
VITE_LOG="$RUNTIME_DIR/vite.log"
COOKIE_FILE="$RUNTIME_DIR/session.cookie"
STUDIO_BASE="/static/studio/"
URL="http://$API_HOST:$VITE_PORT$STUDIO_BASE"

die() { echo "preview: $*" >&2; exit 1; }
info() { echo "preview: $*"; }

[[ "$ROOT_DIR" != "/home/aied/pilot-run" ]] || die "refusing to run inside the pilot worktree"
[[ -x "$PY" ]] || die "missing $PY (create the venv first)"
[[ -f "$ROOT_DIR/studio/package.json" ]] || die "studio/ not found"

alive() { local f="$1"; [[ -f "$f" ]] && kill -0 "$(cat "$f")" 2>/dev/null; }

write_env() {
  mkdir -p "$RUNTIME_DIR/keys" "$RUNTIME_DIR/home" "$RUNTIME_DIR/results"
  chmod 700 "$RUNTIME_DIR"
  # A throwaway private key so the add-compute wizard's key-path validation
  # (SSH_KEY_ALLOWED_DIRS) can pass without touching real credentials.
  if [[ ! -f "$RUNTIME_DIR/keys/preview_key" ]]; then
    ssh-keygen -q -t ed25519 -N "" -C "dispatch-preview" -f "$RUNTIME_DIR/keys/preview_key"
  fi
  if [[ ! -f "$RUNTIME_DIR/.env" ]]; then
    cat > "$RUNTIME_DIR/.env" <<EOF
# generated by .claude/skills/local-preview/scripts/preview.sh — loopback only
API_HOST=$API_HOST
API_PORT=$API_PORT
DB_PATH=$RUNTIME_DIR/jobqueue.db
AUDIT_PATH=$RUNTIME_DIR/audit.jsonl
SERVERS_YAML_PATH=$RUNTIME_DIR/servers.yaml
LOCAL_HOME_DIR=$RUNTIME_DIR
ENV_FILE_PATH=$RUNTIME_DIR/.env
SSH_KEY_ALLOWED_DIRS=$RUNTIME_DIR/keys
AI_USAGE_HOME_DIR=$RUNTIME_DIR/home
AUTHORIZATION_MODE=off
OIDC_ENABLED=false
LEGACY_SHARED_TOKEN_ENABLED=false
SERVICE_TOKEN_AUTH_ENABLED=false
IDENTITY_ADMIN_ENABLED=false
EOF
    chmod 600 "$RUNTIME_DIR/.env"
  fi
}

export_env() {
  # Explicit exports win over any repo-root .env the app would otherwise read.
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    export "$key=$value"
  done < "$RUNTIME_DIR/.env"
}

seed_session() {
  # Seed (idempotently) a human platform-admin actor + long-lived session in
  # the PREVIEW database only, and store the cookie for the Vite proxy.
  "$PY" - "$COOKIE_FILE" <<'PYEOF'
import os, sys, uuid
from app.db import Database
from app.identity import ActorType, generate_session_token

cookie_file = sys.argv[1]
db = Database(os.environ["DB_PATH"])
actor_id = str(uuid.uuid5(uuid.NAMESPACE_URL, "dispatch-center/local-preview/admin"))
actor = db.get_actor(actor_id)
if actor is None:
    actor = db.insert_actor(actor_type=ActorType.HUMAN, display_name="Preview Admin", actor_id=actor_id, platform_admin=True)
issued = generate_session_token()
db.insert_actor_session(session_id=issued.id, actor_id=actor.id, secret_hash=issued.secret_hash, expires_at="2099-01-01T00:00:00+00:00")
cookie_name = os.environ.get("SESSION_COOKIE_NAME", "dispatch_session")
with open(cookie_file, "w", encoding="utf-8") as handle:
    handle.write(f"{cookie_name}={issued.raw_token}")
os.chmod(cookie_file, 0o600)
print(f"preview: seeded actor {actor.display_name} (platform_admin) with a session")
PYEOF
}

wait_http() { # url expected-code seconds
  local url="$1" want="$2" secs="$3" code=""
  for _ in $(seq 1 "$secs"); do
    code=$(curl -s -o /dev/null -w "%{http_code}" "$url" || true)
    [[ "$code" == "$want" ]] && return 0
    sleep 1
  done
  return 1
}

start_backend() {
  if alive "$BACKEND_PID"; then info "backend already running (pid $(cat "$BACKEND_PID"))"; return; fi
  write_env; export_env; seed_session
  # exec so the recorded pid IS the server; every fd redirected so no caller
  # pipe stays open (otherwise the invoking shell hangs waiting for EOF).
  ( cd "$ROOT_DIR" && exec "$PY" -m app.main ) > "$BACKEND_LOG" 2>&1 < /dev/null &
  echo $! > "$BACKEND_PID"
  wait_http "http://$API_HOST:$API_PORT/" 200 30 || { tail -20 "$BACKEND_LOG" >&2; die "backend did not become healthy"; }
  info "backend up: http://$API_HOST:$API_PORT (runtime $RUNTIME_DIR)"
}

start_vite() {
  if alive "$VITE_PID"; then info "vite already running (pid $(cat "$VITE_PID"))"; return; fi
  [[ -d "$ROOT_DIR/studio/node_modules" ]] || ( cd "$ROOT_DIR/studio" && npm ci --no-audit --no-fund )
  ( cd "$ROOT_DIR/studio" && PREVIEW_API_TARGET="http://$API_HOST:$API_PORT" PREVIEW_SESSION_COOKIE="$(cat "$COOKIE_FILE")" \
      exec npx vite --host "$API_HOST" --port "$VITE_PORT" --strictPort ) > "$VITE_LOG" 2>&1 < /dev/null &
  echo $! > "$VITE_PID"
  # Vite serves the Studio under its production base path.
  wait_http "http://$API_HOST:$VITE_PORT$STUDIO_BASE" 200 30 || { tail -20 "$VITE_LOG" >&2; die "vite did not start"; }
  info "studio (hot reload, auto-login): http://$API_HOST:$VITE_PORT$STUDIO_BASE"
}

stop_one() { # pidfile name
  local f="$1" name="$2"
  if alive "$f"; then
    local pid; pid="$(cat "$f")"
    kill "$pid" 2>/dev/null || true
    pkill -P "$pid" 2>/dev/null || true
    for _ in $(seq 1 20); do kill -0 "$pid" 2>/dev/null || break; sleep 0.5; done
    pkill -P "$pid" 2>/dev/null || true
    kill -9 "$pid" 2>/dev/null || true
    info "$name stopped"
  fi
  rm -f "$f"
}

status() {
  for pair in "$BACKEND_PID:backend" "$VITE_PID:vite"; do
    f="${pair%%:*}"; name="${pair##*:}"
    if alive "$f"; then echo "$name: running (pid $(cat "$f"))"; else echo "$name: stopped"; fi
  done
  if alive "$BACKEND_PID"; then
    echo "backend health: $(curl -s -o /dev/null -w "%{http_code}" "http://$API_HOST:$API_PORT/")"
    if [[ -f "$COOKIE_FILE" ]]; then
      echo "api /api/v2/me (with cookie): $(curl -s -o /dev/null -w "%{http_code}" -H "Cookie: $(cat "$COOKIE_FILE")" "http://$API_HOST:$API_PORT/api/v2/me")"
    fi
  fi
  alive "$VITE_PID" && echo "url: $URL   (Compute page: ${URL}#/compute)"
  echo "runtime: $RUNTIME_DIR"
}

case "${1:-status}" in
  start) start_backend; start_vite; status ;;
  stop) stop_one "$VITE_PID" vite; stop_one "$BACKEND_PID" backend ;;
  restart) "$0" stop; "$0" start ;;
  status) status ;;
  logs) tail -n 40 "$BACKEND_LOG" "$VITE_LOG" 2>/dev/null || true ;;
  reset) "$0" stop; rm -rf "$RUNTIME_DIR"; "$0" start ;;
  cookie) cat "$COOKIE_FILE" ;;
  *) die "unknown command: $1 (start|stop|restart|status|logs|reset|cookie)" ;;
esac
